config/routes.rb
Mishmashes::Application.routes.draw do
  get "home/index"

  resources :spams

  root :to => 'home#index'

end

app/models/spam.rb
class Spam < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rand_id = rand(Spam.count)
    @Spam = Spam.first(:conditions => [ "id > ?", @rand_id])
  end

end

app/controllers/spams_controller.rb
class SpamsController < ApplicationController
  # GET /spams
  # GET /spams.json
  def index
    @spams = Spam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spams }
    end
  end

  # GET /spams/1
  # GET /spams/1.json
  def show
    @spam = Spam.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spam }
    end
  end

  # GET /spams/new
  # GET /spams/new.json
  def new
    @spam = Spam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spam }
    end
  end

  # GET /spams/1/edit
  def edit
    @spam = Spam.find(params[:id])
  end

  # POST /spams
  # POST /spams.json
  def create
    @spam = Spam.new(params[:spam])

    respond_to do |format|
      if @spam.save
        format.html { redirect_to @spam, notice: 'Spam was successfully created.' }
        format.json { render json: @spam, status: :created, location: @spam }
      else
        format.html { render action: "new" }
        format.json { render json: @spam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spams/1
  # PUT /spams/1.json
  def update
    @spam = Spam.find(params[:id])

    respond_to do |format|
      if @spam.update_attributes(params[:spam])
        format.html { redirect_to @spam, notice: 'Spam was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @spam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spams/1
  # DELETE /spams/1.json
  def destroy
    @spam = Spam.find(params[:id])
    @spam.destroy

    respond_to do |format|
      format.html { redirect_to spams_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spams_helper.rb
module SpamsHelper
end

app/views/home/index.html.erb
<div id="divWrapper">
	<div id="divSpeechBubble"><div id="divBubbleText"><%= @Spam.spam %></div></div>
	<div id="div312">A <a href="http://threetwelvecreative.com">ThreeTwelve Creative Web Development</a> Project.</div>
    <div id="divTweet">
    	<p style="float:left;padding-top:5px;">Why not </p>
    	<p style="height:40px;width:75px;float:left;padding:0px 5px 0px 5px;"><a style="margin-top:0px;" href="https://twitter.com/share" class="twitter-share-button" data-url="http://mishmash.es" data-text="What do you want your mishmash.es to be?" data-via="3TwelveCreative" data-size="large" data-count="none" data-hashtags="mishmashes">Tweet</a></p>
    	<p style="float:left;padding-top:5px;"> and let us know you were here?</p>
    	<p style="clear:left;">Refresh to see even more awesome spam comments!</p>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mishmashes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="description" content="What are your Mishmash.es going to be? Only YOU can answer that!" />
    <meta property="og:image" content="http://mishmash.es/mishmashesNoField.png" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spams/_form.html.erb
<%= form_for(@spam) do |f| %>
  <% if @spam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spam.errors.count, "error") %> prohibited this spam from being saved:</h2>

      <ul>
      <% @spam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spam %><br />
    <%= f.text_field :spam %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spams/edit.html.erb
<h1>Editing spam</h1>

<%= render 'form' %>

<%= link_to 'Show', @spam %> |
<%= link_to 'Back', spams_path %>

app/views/spams/index.html.erb
<h1>Listing spams</h1>

<table>
  <tr>
    <th>Spam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spams.each do |spam| %>
  <tr>
    <td><%= spam.spam %></td>
    <td><%= link_to 'Show', spam %></td>
    <td><%= link_to 'Edit', edit_spam_path(spam) %></td>
    <td><%= link_to 'Destroy', spam, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spam', new_spam_path %>

app/views/spams/new.html.erb
<h1>New spam</h1>

<%= render 'form' %>

<%= link_to 'Back', spams_path %>

app/views/spams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spam:</b>
  <%= @spam.spam %>
</p>


<%= link_to 'Edit', edit_spam_path(@spam) %> |
<%= link_to 'Back', spams_path %>